name: setup-node
description: "Setup Node.js ‚öôÔ∏è - Cache dependencies ‚ö° - Install dependencies üîß"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js ‚öôÔ∏è
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: "npm"

      - name: Restore npm module cache
        uses: actions/cache/restore@v3
        id: cache-npm-restore
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache_name }}-${{ hashFiles('repo/package-lock.json') }}

      - name: List the state of node modules
        if: ${{ steps.cache-npm-restore.outputs.cache-hit == 'true' }}
        continue-on-error: true
        run: cd $repo_dir && npm list

      - name: Install NodeJS modules
        run: | 
          cd $repo_dir && npm ci
 
      - name: Save npm module cache
        if: ${{ steps.cache-npm-restore.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v3
        id: cache-npm-save
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache_name }}-${{ hashFiles('repo/package-lock.json') }}

      - name: List the state of node modules
        if: ${{ steps.cache-npm-restore.outputs.cache-hit != 'true' }}
        continue-on-error: true
        run: cd $repo_dir && npm list